---

- name: create theme archive on ansible controller
  become: false
  delegate_to: localhost
  archive:
    path: "{{ icingaweb_themes_local_tmp_directory }}/{{ item.key }}"
    dest: "{{ icingaweb_themes_local_tmp_directory }}/{{ item.key }}.zip"
    mode: 0660
    remove: false
    format: zip
    exclude_path:
      - "{{ icingaweb_themes_local_tmp_directory }}/{{ item.key }}/.git*"
    exclusion_patterns:
      - "{{ icingaweb_themes_local_tmp_directory }}/{{ item.key }}/.git*"
  loop:
    "{{ icingaweb_themes | dict2items }}"
  loop_control:
    label: "theme: {{ item.key }}"
  when:
    - item.value['download'] | default('true') | bool
  async: 1000
  poll: 10

- name: define checksums from archive
  become: false
  delegate_to: localhost
  stat:
    path: "{{ icingaweb_themes_local_tmp_directory }}/{{ item.key }}.zip"
    checksum_algorithm: sha256
  register: _theme_checksum
  loop:
    "{{ icingaweb_themes | dict2items }}"
  loop_control:
    label: "theme: {{ item.key }}"

- name: append checksums to icingaweb_themes
  set_fact:
    icingaweb_themes: "{{ icingaweb_themes | append_checksum(_theme_checksum) }}"

- name: update facts
  setup:

- name: propagate themes archives
  become: true
  copy:
    src: "{{ icingaweb_themes_local_tmp_directory }}/{{ item.key }}.zip"
    dest: "{{ icingaweb_themes_remote_tmp_directory }}/"
    mode: 0660
  loop:
    "{{ icingaweb_themes | dict2items }}"
  loop_control:
    label: "theme: {{ item.key }}"
  when:
    - item.value['download'] | default('true') | bool

- name: extract theme archives
  unarchive:
    src: "{{ icingaweb_themes_remote_tmp_directory }}/{{ item.key }}.zip"
    dest: "{{ icingaweb_themes_remote_tmp_directory }}/"
    mode: 0700
    remote_src: true
  loop:
    "{{ icingaweb_themes | dict2items }}"
  loop_control:
    label: "theme: {{ item.key }}"
  when:
    - item.value['download'] | default('true') | bool

- name: copy themes in place
  become: true
  copy:
    src: "{{ icingaweb_themes_remote_tmp_directory }}/{{ item.key }}/"
    dest: "{{ icingaweb_themes_install_dir }}/modules/{{ item.key }}"
    owner: "{{ icingaweb_user }}"
    group: "{{ icingaweb_group }}"
    remote_src: true
    mode: 0750
  loop:
    "{{ icingaweb_themes | dict2items }}"
  loop_control:
    label: "theme: {{ item.key }}"
  when:
    - item.value['download'] | default('true') | bool

- name: create theme checksum
  copy:
    dest: "{{ icingaweb_themes_install_dir }}/modules/{{ item.key }}/.checksum"
    content: "{{ item.value.checksum }}"
    owner: "{{ icingaweb_user }}"
    group: "{{ icingaweb_group }}"
    mode: 0640
  loop:
    "{{ icingaweb_themes | dict2items }}"
  loop_control:
    label: "theme: {{ item.key }}"

- name: enable / disable themes
  become: true
  icingacli:
    state: "{{ 'enable' if item.enabled | default('true') else 'disable' }}"
    command: module
    module_name: "{{ item.key }}"
  loop:
    "{{ icingaweb_themes | dict2items }}"
  loop_control:
    label: "theme: {{ item.key }} - enabled: {{ item.value.enabled | default('False', true) }}"

- name: create custom fact file
  template:
    src: facts.d/icingaweb2_themes.fact.j2
    dest: /etc/ansible/facts.d/icingaweb2_themes.fact
    owner: root
    group: root
    mode: 0755
...
