---
dependency:
  name: galaxy

driver:
  name: docker

#lint: |
#  set -e
#  yamllint .
#  ansible-lint .
#  flake8 .

platforms:
  - name: database
    image: "bodsch/ansible-debian:11"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    docker_host: "${DOCKER_HOST:-unix://run/docker.sock}"
    privileged: true
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - database
    docker_networks:
      - name: icingaweb_themes
        ipam_config:
          - subnet: "10.11.1.0/24"
            gateway: "10.11.1.254"
    networks:
      - name: icingaweb_themes
        ipv4_address: "10.11.1.1"

  # - name: icinga2
  #   image: "bodsch/ansible-${DISTRIBUTION:-debian:10}"
  #   command: ${MOLECULE_DOCKER_COMMAND:-""}
  #   docker_host: "${DOCKER_HOST:-unix://run/docker.sock}"
  #   privileged: true
  #   pre_build_image: true
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #   groups:
  #     - icinga
  #   networks:
  #     - name: icinga
  #       ipv4_address: "10.11.1.2"

  - name: instance
    image: "bodsch/ansible-${DISTRIBUTION:-debian:11}"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    docker_host: "${DOCKER_HOST:-unix://run/docker.sock}"
    privileged: true
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - instance
    published_ports:
      - 80:80
    networks:
      - name: icingaweb_themes
        ipv4_address: "10.11.1.3"

provisioner:
  name: ansible
  ansible_args:
    - --diff
    - -v
  config_options:
    defaults:
      deprecation_warnings: true
      stdout_callback: yaml
      callbacks_enabled: profile_tasks
      gathering: smart
      fact_caching: jsonfile
      fact_caching_timeout: 8640
      fact_caching_connection: ansible_facts

scenario:
  test_sequence:
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - verify
    - destroy

verifier:
  name: testinfra
